runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /tasks/send_emails
  script: sylvierocks.php
  login: admin

- url: /.*
  script: index.php
  secure: always

skip_files:
  - .data/
  - .git/
  - docker/
  - output/
