<h2><?php p('Quốc huy'); ?></h2>
<div class="warning">
	<?php p('Xin lưu ý, tài liệu sau đây chưa xác định được rõ độ tin cậy.'); ?>
	<?php p('Tại đây cũng chỉ xin phép trích lược dựa trên những tài liệu có được.'); ?>
</div>
<div class="text">
	<img id="coa" class="left_image" src="assets/Vietnam_Coat_of_Arms.gif" alt="<?php p('Quốc huy nước Cộng hòa Xã hội Chủ nghĩa Việt Nam'); ?>" title="Quốc huy" width="125" height="125"/>
	<p><?php p('Quốc huy Việt Nam - một sản phẩm của sáng tác hội hoạ, là biểu tượng cô đọng, súc tích và đầy đủ về đất nước và con người Việt Nam, nó hàm chứa khát vọng tha thiết của một dân tộc yêu chuộng hoà bình và khẳng định chủ quyền thiêng liêng của quốc gia độc lập. Tác giả Quốc huy từ mấy chục năm nay được xác định là của Cố hoạ sĩ Trần Văn Cẩn. Tuy nhiên, từ sau ngày 9 tháng 9 năm 2001, khi hoạ sĩ Lê Lam có bài "Người vẽ Quốc huy" đăng trên báo Nhân dân cuối tuần khẳng định: Hoạ sĩ Bùi Trang Chước là người sáng tác và thực hiện các phác thảo Quốc huy... Đặc biệt, khi gia đình cố hoạ sĩ Bùi Trang Chước gửi đơn thư tới các cơ quan chức năng đề nghị xét công nhận tác giả Quốc huy cho Ông Bùi Trang Chước với những tài liệu gốc do gia đình có được hoặc sưu tầm được thì vấn đề đòi hỏi xác định lại tác giả Quốc huy đã thật sự trở nên nóng bỏng và bức xúc. Từ năm 2001 tới nay đã có hàng trăm bài báo, hàng chục cuộc họp của các cơ quan chức năng với gia đình cố hoạ sĩ Bùi Trang Chước để xem xét việc xác định tác giả Quốc huy. Do vậy, một số tài liệu lưu trữ bảo quản tại Trung tâm lưu trữ quốc gia III và cả những tài liệu cá nhân của cố hoạ sĩ Bùi Trang Chước do gia đình biếu tặng đã được đưa ra nghiên cứu, thẩm định.'); ?></p>
	<p><?php p('Họa sĩ Bùi Trang Chước sinh năm 1915 ở Phú Thượng, Từ Liêm, Hà Nội. Ông tốt nghiệp Trường Cao đẳng Mỹ thuật Đông Dương năm 1941. Ông tham gia cuộc vận động sáng tác mẫu Quốc huy Việt Nam được phát động tháng 6-1951. Từ năm 1953 đến 1955, Hoạ sĩ Bùi Trang Chước đã có 94 bản vẽ nghiên cứu, phác thảo và hàng chục bản vẽ chì chi tiết những đối tượng mà ông muốn thể hiện trong mẫu Quốc huy. Từ những nghiên cứu đó, Ông đã hoàn thành 15 bản vẽ mẫu Quốc huy đa dạng nhưng thống nhất về ý tưởng để gửi cấp trên lựa chọn. Đến tháng 10/1954, từ hơn 300 mẫu quốc huy của các hoạ sĩ tham gia, cuối cùng chỉ còn 15 mẫu của tác giả duy nhất là Bùi Trang Chước được lựa chọn để trình Chính phủ. Mẫu số 1 có nền đỏ sao vàng, tượng trưng cho quốc kỳ của Việt Nam dân chủ cộng hoà; mặt trời mọc tượng trưng cho nước ta ở phương Đông, tượng trưng cho buổi bình minh của một kỷ nguyên mới và là tương lai của nền dân chủ cộng hoà; bông lúa tượng trưng cho nông nghiệp và giai cấp nông dân và cái đe tượng trưng cho công nghiệp và giai cấp công nhân (mẫu số 1 qua 3 lần chỉnh sửa sau này trở thành mẫu 18).'); ?></p>
	<p><?php p('Theo Di bút "Tôi vẽ mẫu Quốc huy" của hoạ sĩ Bùi Trang Chước viết ngày 26/4/1985, tiếp thu những ý kiến đóng góp của Chủ tịch Hồ Chí Minh vào mẫu vẽ số 1 - mẫu vẽ cuối cùng trong số 15 mẫu vẽ; "Hình tượng cái đe là thủ công nghiệp cá thể, nên dùng hình tượng tượng trưng cho nền công nghiệp hiện đại" sau 3 lần chỉnh sửa, từ đầu  năm 1955 đến tháng 9/1955, hoạ sĩ Bùi Trang Chước đã hoàn thành mẫu Quốc huy cuối cùng gồm 1 bản màu và 2 bản tách màu đen trắng. Sau khi hoàn thành bản vẽ mẫu Quốc huy cuối cùng này, do nhiệm vụ đặc biệt và tuyệt mật của Chính phủ giao, ông lên đường sang Trung Quốc để vẽ tiền và in tiền. Chính vì vậy, Ông không có điều kiện chỉnh sửa, hoàn thiện Quốc huy theo sự góp ý của Trung ương sau kỳ họp Quốc hội vào tháng 9/1955. Nhiệm vụ chỉnh sửa, hoàn thiện này sau đó được giao cho hoạ sĩ Trần Văn Cẩn.'); ?></p>
	<p><?php p('Một tài liệu lưu trữ rất quan trọng trong Phông Bộ Tuyên truyền là Văn bản số 237/MT ngày 24/11/1954 do chính Hoạ sĩ Trần Văn Cẩn phụ trách Ban Mỹ thuật - Ngành Văn nghệ Trung ương ký, gửi Bộ Tuyên truyền, trong đó cũng khẳng định rõ 15 mẫu mà Ban Mỹ thuật trình Bộ Tuyên truyền là của Họa sĩ Bùi Trang Chước. Văn bản nói rõ: "Khoảng trung tuần tháng 10/54, chúng tôi có gửi sang quí Bộ một số 15 mẫu quốc trưng để quí Bộ đưa trình Thủ Tướng phủ xem và cho ý kiến quyết định. Chúng tôi chờ đợi đã lâu mà chưa có tin tức gì về việc đó. Gần đây Vụ Lễ tân bên Thủ Tướng phủ có cho người dục luôn nên chúng tôi cử  hoạ sĩ Bùi Trang Chước, tác giả những mẫu ấy, sang  đề nghị quý Bộ cho biết tin tức về các mẫu đã được chọn. Cũng đề nghị quí Bộ trao lại cho hoạ sĩ Chước những mẫu đã gửi để đem về sửa lại và hoàn thành".'); ?></p>
	<p><?php p('Tháng 6/2003 Viện Khoa học hình sự - Bộ Công an đã chính thức tiến hành công tác thẩm định và đã trả lời kết quả cho Cục Bản quyền tác giả. Ngày 28/10/2003 Cục Bản quyền tác giả đã thông báo chính thức kết quả giám định khoa học hình sự như sau: "Bản viết tay "Tôi vẽ mẫu Quốc huy" của cố hoạ sĩ Bùi Trang Chước và bản viết tay "Chúng tôi làm Quốc huy" của cố hoạ sĩ Trần Văn Cẩn là do chính các cố hoạ sĩ viết".'); ?></p>
	<p><?php p('Ba tuần sau đó, ngày 19/11/2003 bằng Văn bản số 227/BQTG-VHNT, Cục Bản quyền tác giả cho rằng: "Kết quả giám định đó không trái với các nguồn tư liệu, chứng cứ và các ý kiến đã được các thành viên trong tổ Tư vấn và những người có liên quan trao đổi, thảo luận. Kết quả giám định cũng phù hợp với ý kiến của đa số thành viên của Tổ Tư vấn và ý kiến của Bộ Văn hoá - Thông tin, làm rõ hơn căn cứ xác định tác giả Quốc huy Việt Nam. Vì vậy Bộ Văn hoá - Thông tin cho rằng Quốc huy Việt Nam do đồng tác giả sáng tạo gồm cố hoạ sĩ Bùi Trang Chước và cố họa sĩ Trần Văn Cẩn là kết luận thoả đáng và hoàn toàn có căn cứ. Bộ trưởng Bộ Văn hoá - Thông tin đã báo cáo Thủ tướng Chính phủ xem xét, quyết định".'); ?></p>
	<p><?php p('Ngày 9/2/2004, tại cuộc họp, sau khi nghe đại diện Bộ Văn hoá - Thông tin báo cáo, nghe ý kiến cuả các Phó Thủ tướng và ý kiến của các đại biểu dự họp, Thủ tướng Phan Văn Khải đã có ý kiến kết luận. Ngày 27/02/2004 Văn phòng Chính phủ đã có Công văn số 42/TB-VPCP thông báo ý kiến của Thủ tướng Phan Văn Khải tại cuộc họp về việc xác định tác giả vẽ mẫu Quốc huy Việt Nam như sau:  "Việc xây dựng mẫu Quốc huy Việt Nam được thực hiện theo chủ trương của Bác Hồ, Đảng và Nhà nước ta. Mẫu Quốc huy Việt Nam là một cống hiến chung của giới mỹ thuật Cách mạng Việt Nam, trong đó  phải kể đến công lao của hoạ sĩ Bùi Trang Chước - người đã vẽ những mẫu Quốc huy để làm cơ sở lựa chọn, hoàn thiện, và hoạ sĩ Trần Văn Cẩn - người đã chỉnh sửa, hoàn thiện mẫu Quốc huy theo ý kiến chỉ đạo của lãnh đạo để trình Quốc hội phê duyệt. Giao Bộ trưởng Bộ Văn hoá - Thông tin có văn bản báo cáo Uỷ ban Thường vụ Quốc hội về vấn đề tác giả vẽ mẫu Quốc huy Việt Nam".'); ?></p>
</div>
<div class="source">
<?php p('Nguồn'); ?>:
<a href="http://www.chinhphu.vn/cttdtcp/vi/nuocchxhcnvn/thongtintonghop/thongtintonghop.html" target="_blank">chinhphu.vn</a>,
<a href="http://www.lichsuvietnam.vn/home.php?option=com_content&task=view&id=1091&Itemid=69" target="_blank">lichsuvietnam.vn</a>
</div>